version: '3.8'

services:
  ruby:
    build: .
    volumes:
      - .:/app
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test_database
